### ISSUE TITLE
implement questions / form page

### ISSUE THREAD

**Issue by AHaliq** [smucclaw/vue-pure-pdpa#22]
@tws4793 please fill in the requirements for this page

also specify the interaction with `AnyAll` library

@Meowyam feel free to work with @tws4793 and branch if necessary to include ur animation and checkboxes component in the form page (referencing #14)

**Comment by AHaliq** [comment]
also do make new sub issues referencing this issue to breakup the scope into smaller components after you have finalized the requirements

**Comment by mengwong** [comment]
I have done initial implementation by integrating against the AnyAll library, in the `anyall` branch, which I am ready to merge to main. Next we will need animations for gradual grey/shrink vs white/expand, and I want to import @tws4793 's work on the Bulma buttons so the radiobuttons show up against a slightly larger widget.

**Comment by mengwong** [comment]
Initial implementation of PDPA is done: http://localhost:8080/pdpa
