### ISSUE TITLE
Pugjs integration

### ISSUE THREAD

**Issue by AHaliq** [smucclaw/vue-pure-pdpa#9]
Looking at this [article](https://blog.logrocket.com/using-pug-js-with-vue-js/?ref=morioh.com&utm_source=morioh.com) pug is compiled to an html file. Thus in Vue framework it can only be used as the top level html replacing `public/index.html`.

My initial thoughts were that we could write in pug syntax inside `.vue` files' templates.

This makes the use of pug very minimal.

Let me know we both have the same understanding. Otherwise make a branch and perhaps show an example of pug syntax being used in vue. @tws4793

**Comment by tws4793** [comment]
Yes it's possible to write pug syntax inside `.vue` templates, e.g.

```vue
<template lang="pug">
.columns
  .column
    h1 Hello World
</template>
```

**Comment by AHaliq** [comment]
ok got it, this [plugin](https://www.npmjs.com/package/vue-cli-plugin-pug) made it straightforward
